### ISSUE TITLE
添加检索标题

### ISSUE THREAD

**Issue by git-zxx** [fatevase/SiYuanDailyViews#1]
我使用的是Dark+主题，我觉得这个挂件很好用，但是，他把我在笔记中的批注内容给检索出来显示了 [呆住.jpg]。我想，可以设置成检索前三个一级标题吗？标题概括性应该也不错，可是我又不会改，只能等更新啦，如果能采纳就太好了

**Comment by fatevase** [comment]
尝试下看有没有修复检索标签的问题

**Comment by fatevase** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 哇，效率太高了！非常感谢，我去看一哈 ***@***.***
> […](#)
😂 就是集市还没被合并，你可以先从git上下载试试。

**Comment by git-zxx** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        刚刚我又测试了一下，发现几个情况：
        我今天创建的批注 不会被检索之前创建的批注 会被检索我本打算给您提供一份markdown文件用于测试，但是我创建了文件之后，我发现我这里也检索不到新建的批注，但是之前创建的批注却仍然被检索到，而且只显示一条有个文档中有多个批注，我重新创建被检索到的批注，结果会检索到下一个批注，应该就是只会检索之前创建的批注内容，我明天再测试一下是不是这样您也可以在集市下载Dark+主题然后选中文字→创建批注，我这里出现的问题就是Dark+主题创建的批注被检索到了，但是今天创建的又不会被检索到，有点迷哈哈哈哈
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年5月23日 09:50
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [fatevase/SiYuanDailyViews] 检索内容 (Issue #1)
        
      
    
  
  







关于批注问题









可以给我个测试用的markdown格式的文件嘛，我测试一下。









关于检索一级标签









现在前几次更新插件还在等反馈把bug修复差不多了(一直没反馈我这边也不清楚有什么bug就暂时不引入新的东西)，后续会添加个浮窗用来显示一些详细的信息。
