### ISSUE TITLE
日记目录格式不同导致检索失败

### ISSUE THREAD

**Issue by winter60** [fatevase/SiYuanDailyViews#2]
![image](https://user-images.githubusercontent.com/23653326/169735373-7c32f8aa-9a32-4168-9d30-a84df034b045.png)

**Comment by fatevase** [comment]
我的锅，我在检索日记名称那里默认为`year-month-day`，今天晚上修复这个问题，改成检索的形式。

**Comment by fatevase** [comment]
现在可以尝试一下，应该修复了。

**Comment by winter60** [comment]
> 现在可以尝试一下，应该修复了。

可👍
