### ISSUE TITLE
不显示标签

### ISSUE THREAD

**Issue by whzecomjm** [fatevase/SiYuanDailyViews#4]
感谢提供这个插件。目前发现有些标签无法显示（仅仅只有写在很前面的标签可以）。

![image](https://user-images.githubusercontent.com/7845827/169815122-cd835410-26c1-419b-b800-2e57f6226075.png)

**Comment by fatevase** [comment]
发现有些标签的父级不是文档下，导致无法检索到标签，自己感觉不应该再检索子集下的标签。
方便提供测试文档给我做下测试吗

**Comment by whzecomjm** [comment]
> 

谢谢 那我应该知道原因了。我一般标签都写在文章末尾。因此相当于是某个二级甚至更低级标题内。

但是似乎标在标题封面处的的标签页无法检索。
![image](https://user-images.githubusercontent.com/7845827/170807586-b39b84ac-152b-4767-8549-57af520eef8d.png)

**Comment by fatevase** [comment]
> 谢谢 那我应该知道原因了。我一般标签都写在文章末尾。因此相当于是某个二级甚至更低级标题内。
> 
> 但是似乎标在标题封面处的的标签页无法检索。 ![image](https://user-images.githubusercontent.com/7845827/170807586-b39b84ac-152b-4767-8549-57af520eef8d.png)


你现在可以在检查下看bug存不存在了，前几天修了一些bug。

**Comment by fatevase** [comment]
刚测试了一下，可以正常检索到，问题就彻底关闭了。
