### ISSUE TITLE
添加按时间检索当天笔记

### ISSUE THREAD

**Issue by hito0512** [fatevase/SiYuanDailyViews#5]
![捕获](https://user-images.githubusercontent.com/26110883/171526303-e15930ba-d38a-4bac-8a97-65677ab2c786.JPG)
笔记目录是这种格式的，无法显示其中任何一篇

**Comment by fatevase** [comment]
你是把日记的时间的标题都换成了其他的名字了是吗😨

**Comment by hito0512** [comment]
@fatevase 是的，我的笔记格式没有像思源日记那种嵌套格式。时间标题我觉得很不清晰，嵌套太多，所以我没有采用这种方式。

**Comment by fatevase** [comment]
> @fatevase 是的，我的笔记格式没有像思源日记那种嵌套格式。时间标题我觉得很不清晰，嵌套太多，所以我没有采用这种方式。

可以， 我考虑下在没有日记本的前提下按时间检索并显示在日记上，但这会带来一个问题就是一天只能显示一篇文章，过多会无法显示。

**Comment by fatevase** [comment]
> @fatevase 是的，我的笔记格式没有像思源日记那种嵌套格式。时间标题我觉得很不清晰，嵌套太多，所以我没有采用这种方式。

暂不知道实现了后续会不会有什么问题，我会在0.14版里加这个东西，等你反馈修完bug后再上架挂件集市。稍后实现了会联系你试一下。

不过，建议可以尝试下默认格式的日记，如果使用挂件的话，在挂件中第一个一级标题会是显示名称。

**Comment by hito0512** [comment]
> > @fatevase 是的，我的笔记格式没有像思源日记那种嵌套格式。时间标题我觉得很不清晰，嵌套太多，所以我没有采用这种方式。
> 
> 暂不知道实现了后续会不会有什么问题，我会在0.14版里加这个东西，等你反馈修完bug后再上架挂件集市。稍后实现了会联系你试一下。
> 
> 不过，建议可以尝试下默认格式的日记，如果使用挂件的话，在挂件中第一个一级标题会是显示名称。

O(∩_∩)O哈哈~，这个只是我的小众需求，大佬还是考虑大众化的需求吧，感谢大佬的回复。

**Comment by fatevase** [comment]
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/20919830/171547988-1227849e-39cf-49dd-bf14-371ed338ad54.png">
1. 试着实现了一下，但是我的笔记的形式不是按日期而是按内容划分在不同的笔记盒子里，按日期检索对应的笔记盒子内容过于离散...，可能你的会显示的更好看一些。 🤔
2. 这个需求实现和用起来有点奇怪(感觉像一个独立的挂件，专门按日期去索引所有笔记本会好点)，就暂时不更新集市了，不过你可以从git里下载然后自己放在`/data/widget/Daily Views` 中。👌
3. 还是像上述的，可以用来检索全局的笔记像一个独立的挂件。🥲
4. 如果需要索引感觉还是需要一些额外的标签打在文章中，不过这样又回到了最初的问题上，为什么不直接以日记的形式存储，然后以h1标题作为显示主题。🤯
5. 可以以用日记的格式做索引，在h1中显示主要内容，通过标签或者h2内容给子内容做索引。🫣

**Comment by hito0512** [comment]
好的，感谢

**Comment by hito0512** [comment]
再次感谢，测试了一下，基本是我所希望的那样


| |
杨桃
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年6月2日 11:52 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [fatevase/SiYuanDailyViews] 没有日记情况下按时间检索笔记 (Issue #5) |

1. 试着实现了一下，但是我的笔记的形式不是按日期而是按内容划分在不同的笔记盒子里，按日期检索对应的笔记盒子内容过于离散...，可能你的会显示的更好看一些。 🤔 2. 这个需求实现和用起来有点奇怪(感觉像一个独立的挂件，专门按日期去索引所有笔记本会好点)，就暂时不更新集市了，不过你可以从git里下载然后自己放在`/data/widget/Daily Views` 中。👌 3. 还是像上述的，可以用来检索全局的笔记像一个独立的挂件。🥲 4. 如果需要索引感觉还是需要一些额外的标签打在文章中，不过这样又回到了最初的问题上，为什么不直接以日记的形式存储，然后以h1标题作为显示主题。🤯 5. 可以以用日记的格式做索引，在h1中显示主要内容，通过标签或者h2内容给子内容做索引。🫣

**Comment by hito0512** [comment]
> 暂时打开，想了一下之后这个功能可以做成单独的渲染方式，通过按钮进行切换可能会好点。 最近空闲可以试试实现。

其实，这种显示方式就是最普遍的显示方式，就是任何一个笔记本都可以显示，无论你是哪种格式的笔记，只要按照H1标题进行显示就好了。正如我先前所说的，如果用日记本那种格式，需要年，月，日，三个层级，如果再加上额外的需求的话可能就会有四级目录，我觉得这太麻烦了，我比较喜欢清爽的，所以这种通用格式的显示方式就可以满足。

**Comment by hito0512** [comment]
![捕获](https://user-images.githubusercontent.com/26110883/171573012-63825fe3-a285-45c5-8377-68dd6082c485.JPG)
大佬，有一个这样的想法，觉得有必要做一个插件吗？就是如上图显示的那样，统计了本地的文章数量，标签，以及分类，然后下面把一些常用的网址链接放上，然后这个界面的右侧将笔记本的目录进行显示，下面可以显示最新写的文章啥的，整体看起来更像是一个网页，O(∩_∩)O哈哈~，只是想让笔记本更有趣点，反正思源笔记可以自定义插件。其实我是希望这个插件能作为一个笔记的入口，奈何自己不太会弄。 😂

**Comment by fatevase** [comment]
> > 暂时打开，想了一下之后这个功能可以做成单独的渲染方式，通过按钮进行切换可能会好点。 最近空闲可以试试实现。
> 
> 其实，这种显示方式就是最普遍的显示方式，就是任何一个笔记本都可以显示，无论你是哪种格式的笔记，只要按照H1标题进行显示就好了。正如我先前所说的，如果用日记本那种格式，需要年，月，日，三个层级，如果再加上额外的需求的话可能就会有四级目录，我觉得这太麻烦了，我比较喜欢清爽的，所以这种通用格式的显示方式就可以满足。

这次更新应该差不多实现你说的东西了，现在可以切换渲染。

就是因为你说的几个日记带来的多层目录，导致不好查找所以才有了现在做的挂件。

**Comment by fatevase** [comment]
> ![捕获](https://user-images.githubusercontent.com/26110883/171573012-63825fe3-a285-45c5-8377-68dd6082c485.JPG)
> 大佬，有一个这样的想法，觉得有必要做一个插件吗？就是如上图显示的那样，统计了本地的文章数量，标签，以及分类，然后下面把一些常用的网址链接放上，然后这个界面的右侧将笔记本的目录进行显示，下面可以显示最新写的文章啥的，整体看起来更像是一个网页，O(∩_∩)O哈哈~，只是想让笔记本更有趣点，反正思源笔记可以自定义插件。其实我是希望这个插件能作为一个笔记的入口，奈何自己不太会弄。 😂


我看集市里有人做统计相关的挂件，我就暂时不做了🫣
